services:
  postgres:
    container_name: postgres-micromarket-v1
    image: postgres
    environment:
      POSTGRES_USER: sahan
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5400:5432"
    networks:
      - postgres-micromarket-v1
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-micromarket-v1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5000:80"
    networks:
      - postgres-micromarket-v1
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  postgres-micromarket-v1:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: